// ============================================================
// Module 7: Mosca Theorem Calculator (Industry Presets & Reports)
// ============================================================

import type { MoscaResult } from '@/types';

export const MoscaCalcModule = {
  container: null as HTMLElement | null,
  x: 3, // Migration time (years)
  y: 7, // Shelf-life (years)
  z: 6, // Q-Day estimate (years)
  selectedPreset: 'custom' as 'custom' | 'finance' | 'health' | 'defense' | 'ecommerce',

  mount(el: HTMLElement): void {
    this.container = el;
    this.render();
  },

  update(): void {
    this.render();
  },

  applyPreset(preset: 'finance' | 'health' | 'defense' | 'ecommerce'): void {
    this.selectedPreset = preset;
    switch (preset) {
      case 'finance':
        this.y = 10;
        this.x = 4;
        this.z = 6;
        break;
      case 'health':
        this.y = 25;
        this.x = 5;
        this.z = 6;
        break;
      case 'defense':
        this.y = 30;
        this.x = 8;
        this.z = 6;
        break;
      case 'ecommerce':
        this.y = 4;
        this.x = 2;
        this.z = 6;
        break;
    }
    this.render();
  },

  calculate(): MoscaResult {
    const totalExposure = this.x + this.y;
    const isAtRisk = totalExposure > this.z;
    const delta = totalExposure - this.z;

    let riskLevel: MoscaResult['riskLevel'] = 'low';
    let message = 'Your systems are well-positioned before Q-Day.';

    if (delta > 5) {
      riskLevel = 'critical';
      message = `CRITICAL: Your data will be exposed ${delta} years before migration completes!`;
    } else if (delta > 0) {
      riskLevel = 'high';
      message = `HIGH RISK: Migration must start immediately. Exposure window is ${delta} years.`;
    } else if (delta === 0) {
      riskLevel = 'medium';
      message = 'BORDERLINE: Zero margin for error. Any migration delay creates vulnerability.';
    }

    return {
      x: this.x,
      y: this.y,
      z: this.z,
      isAtRisk,
      riskLevel,
      message,
    };
  },

  generateReport(): string {
    const res = this.calculate();
    return `# Mosca's Theorem Quantum Risk Assessment Report
Generated by ZentyRecon (https://ctar.tech)
Date: ${new Date().toISOString()}

---

## Assessment Inputs:
- Migration Time (X): ${this.x} Years
- Data Shelf-Life (Y): ${this.y} Years
- Estimated Time to Q-Day (Z): ${this.z} Years (Est: ~${new Date().getFullYear() + this.z})

## Mosca Equation Evaluation:
X + Y = ${this.x + this.y} Years
Z = ${this.z} Years
Formula Outcome: ${this.x} + ${this.y} ${res.isAtRisk ? '>' : '≤'} ${this.z}

## Risk Verdict:
- Level: ${res.riskLevel.toUpperCase()}
- Exposure Window: ${Math.max(0, this.x + this.y - this.z)} Years
- Verdict: ${res.message}

## Recommendation:
${res.isAtRisk
  ? 'URGENT: Deploy NIST FIPS 203 (ML-KEM/Kyber) hybrid key exchange immediately to defeat Harvest Now, Decrypt Later (HNDL) adversaries.'
  : 'MAINTAIN: Ensure post-quantum migration roadmaps remain on schedule.'
}
`;
  },

  render(): void {
    if (!this.container) return;

    const res = this.calculate();
    const riskBadge = res.riskLevel === 'critical'
      ? 'background: rgba(239,68,68,0.2); color: #ef4444; border: 1px solid rgba(239,68,68,0.4);'
      : res.riskLevel === 'high'
      ? 'background: rgba(245,158,11,0.2); color: #f59e0b; border: 1px solid rgba(245,158,11,0.4);'
      : 'background: rgba(16,185,129,0.2); color: #10b981; border: 1px solid rgba(16,185,129,0.4);';

    this.container.innerHTML = `
      <div class="zr-card">
        <div class="card-header">
          <span class="card-title">Mosca's Theorem (X + Y > Z)</span>
          <span class="badge" style="${riskBadge}">${res.riskLevel.toUpperCase()}</span>
        </div>
        <p style="font-size: 11px; color: var(--muted); margin-bottom: 8px;">
          Determines if sensitive data will be compromised by quantum computers before post-quantum migration completes.
        </p>

        <!-- Industry Presets -->
        <div style="font-size: 10px; color: var(--muted); text-transform: uppercase; margin-bottom: 4px;">Industry Presets</div>
        <div style="display: flex; gap: 4px; margin-bottom: 12px; overflow-x: auto;">
          <button class="preset-btn copy-btn ${this.selectedPreset === 'finance' ? 'active' : ''}" data-preset="finance">Banking</button>
          <button class="preset-btn copy-btn ${this.selectedPreset === 'health' ? 'active' : ''}" data-preset="health">Healthcare</button>
          <button class="preset-btn copy-btn ${this.selectedPreset === 'defense' ? 'active' : ''}" data-preset="defense">Defense</button>
          <button class="preset-btn copy-btn ${this.selectedPreset === 'ecommerce' ? 'active' : ''}" data-preset="ecommerce">E-Commerce</button>
        </div>

        <!-- Sliders -->
        <div style="display: flex; flex-direction: column; gap: 10px;">
          <div>
            <div style="display: flex; justify-content: space-between; font-size: 11px; margin-bottom: 2px;">
              <span>X: Migration Time</span>
              <span class="mono" style="color: #a78bfa; font-weight: 700;">${this.x} Years</span>
            </div>
            <input type="range" id="slider-x" min="1" max="15" value="${this.x}" style="width: 100%; accent-color: #8b5cf6;">
          </div>

          <div>
            <div style="display: flex; justify-content: space-between; font-size: 11px; margin-bottom: 2px;">
              <span>Y: Data Shelf-Life</span>
              <span class="mono" style="color: #38bdf8; font-weight: 700;">${this.y} Years</span>
            </div>
            <input type="range" id="slider-y" min="1" max="35" value="${this.y}" style="width: 100%; accent-color: #06b6d4;">
          </div>

          <div>
            <div style="display: flex; justify-content: space-between; font-size: 11px; margin-bottom: 2px;">
              <span>Z: Estimated Time to Q-Day</span>
              <span class="mono" style="color: #ec4899; font-weight: 700;">${this.z} Years (~${new Date().getFullYear() + this.z})</span>
            </div>
            <input type="range" id="slider-z" min="2" max="20" value="${this.z}" style="width: 100%; accent-color: #ec4899;">
          </div>
        </div>
      </div>

      <!-- Result Card -->
      <div class="zr-card" style="text-align: center;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <span style="font-size: 10px; color: var(--muted); text-transform: uppercase;">Equation Outcome</span>
          <button id="btn-export-mosca" class="copy-btn">Export Report</button>
        </div>
        <div class="mono" style="font-size: 17px; font-weight: 800; color: ${res.isAtRisk ? '#ef4444' : '#10b981'}; margin-top: 6px;">
          ${this.x} + ${this.y} ${res.isAtRisk ? '>' : '≤'} ${this.z} (${this.x + this.y} vs ${this.z} yrs)
        </div>
        <div style="font-size: 11px; margin-top: 6px; color: var(--text); font-weight: 600;">
          ${res.message}
        </div>
      </div>

      <!-- Action Plan -->
      <div class="zr-card">
        <div class="card-header">
          <span class="card-title">HNDL Risk Analysis</span>
          <span class="badge badge-pro">Advisory</span>
        </div>
        <div style="font-size: 11px; color: var(--muted); line-height: 1.6;">
          ${res.isAtRisk
            ? '⚠️ <strong style="color: #ef4444;">Harvest Now, Decrypt Later (HNDL)</strong> attack in progress. Encrypted sessions intercepted today will be decrypted when Q-Day arrives. Implement hybrid ML-KEM to protect secrets whose lifespan exceeds the Q-Day threshold.'
            : '✅ Migration runway is currently adequate. Re-evaluate annually as quantum hardware milestones evolve.'
          }
        </div>
      </div>
    `;

    this.bindEvents();
  },

  bindEvents(): void {
    if (!this.container) return;

    this.container.querySelectorAll<HTMLButtonElement>('.preset-btn').forEach((btn) => {
      btn.addEventListener('click', () => {
        const p = btn.dataset.preset as 'finance' | 'health' | 'defense' | 'ecommerce';
        if (p) this.applyPreset(p);
      });
    });

    this.container.querySelector('#slider-x')?.addEventListener('input', (e) => {
      this.x = parseInt((e.target as HTMLInputElement).value, 10);
      this.selectedPreset = 'custom';
      this.render();
    });

    this.container.querySelector('#slider-y')?.addEventListener('input', (e) => {
      this.y = parseInt((e.target as HTMLInputElement).value, 10);
      this.selectedPreset = 'custom';
      this.render();
    });

    this.container.querySelector('#slider-z')?.addEventListener('input', (e) => {
      this.z = parseInt((e.target as HTMLInputElement).value, 10);
      this.selectedPreset = 'custom';
      this.render();
    });

    this.container.querySelector('#btn-export-mosca')?.addEventListener('click', () => {
      const rep = this.generateReport();
      const blob = new Blob([rep], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `mosca-risk-report-${Date.now()}.md`;
      a.click();
      URL.revokeObjectURL(url);
    });
  },
};
